name: scenicplus_obj
channels:
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - _r-mutex=1.0.1=anacondar_1
  - adjusttext=1.3.0=pyhd8ed1ab_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.3=py311h55b9665_0
  - aiohttp-cors=0.8.1=pyhd8ed1ab_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alsa-lib=1.2.15.1=hb03c661_0
  - anndata=0.11.4=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - arboreto=0.1.6=pyh3252c3a_0
  - arpack=3.9.1=nompi_hf03ea27_102
  - array-api-compat=1.13.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.0=h92a005d_16
  - aws-c-cal=0.9.2=he7b75e1_1
  - aws-c-common=0.12.4=hb03c661_0
  - aws-c-compression=0.3.1=h92c474e_6
  - aws-c-event-stream=0.5.5=h0c2b49e_1
  - aws-c-http=0.10.2=hee85082_3
  - aws-c-io=0.21.0=h1d8da38_1
  - aws-c-mqtt=0.13.1=h46c1de9_4
  - aws-c-s3=0.8.3=h9cdc349_1
  - aws-c-sdkutils=0.2.4=h92c474e_1
  - aws-checksums=0.2.7=h92c474e_2
  - aws-crt-cpp=0.32.10=h186f887_3
  - aws-sdk-cpp=1.11.510=h379b65b_14
  - azure-core-cpp=1.14.0=h5cfcd09_0
  - azure-identity-cpp=1.10.0=h113e628_0
  - azure-storage-blobs-cpp=12.13.0=h3cf044e_1
  - azure-storage-common-cpp=12.8.0=h736e048_1
  - azure-storage-files-datalake-cpp=12.12.0=ha633028_1
  - bbknn=1.6.0=py311h6cce608_5
  - beautifulsoup4=4.14.3=pyha770c72_0
  - bedtools=2.31.1=h13024bc_3
  - bidict=0.23.1=pyhd8ed1ab_1
  - binutils_impl_linux-64=2.45=default_hfdba357_105
  - bokeh=3.8.1=pyhd8ed1ab_0
  - boltons=25.0.0=pyhd8ed1ab_0
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - brotli-python=1.1.0=py311h1ddb823_4
  - bs4=4.14.3=hd8ed1ab_0
  - bwidget=1.10.1=ha770c72_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=6.2.4=pyhd8ed1ab_0
  - cairo=1.18.4=h3394656_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py311h03d9500_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - colorful=0.5.8=pyhd8ed1ab_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.2=py311hd18a35c_0
  - cpython=3.11.14=py311hd8ed1ab_2
  - cryptography=46.0.3=py311h2005dd1_1
  - ctxcore=0.2.0=pyh7e72e81_1
  - curl=8.17.0=h4e3cde8_1
  - cycler=0.12.1=pyhcf101f3_2
  - cytoolz=1.1.0=py311h49ec1c0_1
  - dask=2023.4.1=pyhd8ed1ab_0
  - dask-core=2023.4.1=pyhd8ed1ab_0
  - dataclasses-json=0.6.7=pyhcf101f3_2
  - debugpy=1.8.19=py311hdb0dbe3_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - deprecated=1.3.1=pyhd8ed1ab_0
  - dill=0.4.0=pyhcf101f3_1
  - distlib=0.4.0=pyhd8ed1ab_0
  - distributed=2023.4.1=pyhd8ed1ab_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fbpca=1.0=pyhd8ed1ab_1
  - filelock=3.20.2=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py311h3778330_0
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - frozendict=2.4.7=py311h49ec1c0_0
  - frozenlist=1.7.0=py311h52bc045_0
  - fsspec=2025.12.0=pyhd8ed1ab_0
  - future=1.0.0=pyhd8ed1ab_2
  - gcc_impl_linux-64=15.2.0=hc5723f1_16
  - gensim=4.3.3=py311h4a3439e_0
  - geosketch=1.3=pyhdfd78af_0
  - gflags=2.2.2=h5888daf_1005
  - gfortran_impl_linux-64=15.2.0=h281d09f_16
  - giflib=5.2.2=hd590300_0
  - globre=0.1.5=pyhd8ed1ab_1
  - glog=0.7.1=hbabe93e_0
  - glpk=5.0=h445213a_0
  - gmp=6.3.0=hac33072_2
  - google-api-core=2.28.1=pyhd8ed1ab_0
  - google-auth=2.45.0=pyhd8ed1ab_0
  - googleapis-common-protos=1.72.0=pyhd8ed1ab_0
  - graphite2=1.3.14=hecca717_2
  - grpcio=1.71.0=py311h8825b61_1
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=15.2.0=hda75c37_16
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.15.1=nompi_py311h0b2f468_101
  - harfbuzz=12.2.0=h15599e2_0
  - harmonypy=0.0.10=pyhdfd78af_0
  - hdf5=1.14.6=nompi_h1b119a7_104
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - igraph=0.10.16=h98b0679_0
  - imagecodecs-lite=2019.12.3=py311h18e1886_8
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_metadata=8.7.0=h40b2b14_1
  - interlap=0.2.7=pyh9f0ad1d_0
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.8.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - kernel-headers_linux-64=6.12.0=he073ed8_5
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py311h724c32c_2
  - krb5=1.21.3=h659f571_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - legacy-api-wrap=1.5=pyhd8ed1ab_0
  - leidenalg=0.10.2=py311h1ddb823_1
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250127.1=cxx17_hbbce691_0
  - libaec=1.1.4=h3f801dc_0
  - libarrow=20.0.0=h1b9301b_8_cpu
  - libarrow-acero=20.0.0=hcb10f89_8_cpu
  - libarrow-dataset=20.0.0=hcb10f89_8_cpu
  - libarrow-substrait=20.0.0=h1bed206_8_cpu
  - libblas=3.9.0=20_linux64_openblas
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcblas=3.9.0=20_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.17.0=h4e3cde8_1
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-devel_linux-64=15.2.0=hcc6f6b0_116
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libglib=2.86.3=h6548e54_0
  - libgomp=15.2.0=he0feb66_16
  - libgoogle-cloud=2.36.0=hc4361e1_1
  - libgoogle-cloud-storage=2.36.0=h0121fbd_1
  - libgrpc=1.71.0=h8e591d7_1
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.9.0=20_linux64_openblas
  - libleidenalg=0.11.1=h00ab1b0_0
  - libllvm14=14.0.6=hcd5def8_4
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libopentelemetry-cpp=1.21.0=hd1b1c89_0
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_0
  - libparquet=20.0.0=h081d1f1_8_cpu
  - libpng=1.6.53=h421ea60_0
  - libprotobuf=5.29.3=h7460b1f_3
  - libre2-11=2025.06.26=hba17884_0
  - libsanitizer=15.2.0=h90f66d4_16
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.1=h0c1763c_1
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-devel_linux-64=15.2.0=hd446a21_116
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libthrift=0.21.0=h0e7cc3e_0
  - libtiff=4.7.1=h9d88235_1
  - libunwind=1.8.3=h65a8314_0
  - libutf8proc=2.10.0=h202a827_0
  - libuuid=2.41.3=h5347b49_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.9=h04c0eec_0
  - libxslt=1.1.43=h7a3aeb2_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.42.0=py311ha6695c7_1
  - locket=1.0.0=pyhd8ed1ab_0
  - loompy=3.0.8=pyhd8ed1ab_0
  - loomxpy=0.4.2=pyhdfd78af_0
  - lxml=6.0.2=py311hc53b721_0
  - lz4=4.4.5=py311h1c460e0_1
  - lz4-c=1.10.0=h5888daf_1
  - macs2=2.2.9.1=py311haab0aaa_5
  - make=4.4.1=hb9d3cd8_2
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py311h3778330_0
  - marshmallow=3.26.1=pyhd8ed1ab_0
  - matplotlib-base=3.6.3=py311h8597a09_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - msgpack-python=1.1.2=py311hdf67eae_1
  - multidict=6.7.0=py311h3778330_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mypy_extensions=1.1.0=pyha770c72_0
  - narwhals=2.14.0=pyhcf101f3_0
  - natsort=8.4.0=pyh29332c3_1
  - ncls=0.0.70=py311haab0aaa_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4=pyhd8ed1ab_0
  - nlohmann_json=3.12.0=h54a6638_1
  - nomkl=1.0=h5ca1d4c_0
  - numba=0.59.1=py311h96b013e_0
  - numexpr=2.14.1=py311h3143de2_101
  - numpy=1.23.5=py311h7d28db0_0
  - numpy_groupies=0.11.3=pyhd8ed1ab_0
  - opencensus=0.11.3=pyhd8ed1ab_1
  - opencensus-context=0.1.3=py311h38be061_4
  - openjdk=25.0.1=h5755bd7_0
  - openjpeg=2.5.4=h55fea9a_0
  - openpyxl=3.1.5=py311h534898f_2
  - openssl=3.6.0=h26f9b46_0
  - opentelemetry-api=1.39.1=pyhd8ed1ab_0
  - opentelemetry-exporter-prometheus=0.60b1=pyhcf101f3_0
  - opentelemetry-proto=1.39.1=pyhd8ed1ab_0
  - opentelemetry-sdk=1.39.1=pyhd8ed1ab_0
  - opentelemetry-semantic-conventions=0.60b1=pyhd8ed1ab_0
  - orc=2.1.2=h17f744e_0
  - packaging=25.0=pyh29332c3_1
  - pandas=1.5.3=py311h2872171_1
  - pango=1.56.4=hadf4263_0
  - parso=0.8.5=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.47=haa7fec5_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=12.1.0=py311hf88fc01_0
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - polars=1.36.1=pyh6a1acc5_0
  - polars-runtime-32=1.36.1=py310hffdcd12_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py311h2dc5d0c_0
  - proto-plus=1.27.0=pyhd8ed1ab_0
  - protobuf=5.29.3=py311h3a6f5f3_0
  - psutil=7.2.1=py311haee01d2_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-spy=0.4.1=he182f42_0
  - pyarrow=20.0.0=py311h38be061_0
  - pyarrow-core=20.0.0=py311h4854187_0_cpu
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pybedtools=0.12.0=py311h2de2dd3_0
  - pybigtools=0.2.4=py311h33b73ba_0
  - pybigwig=0.3.22=py311h1833357_4
  - pybiomart=0.2.0=pyh864c0ab_1
  - pycistopic=2.0a=pyhdfd78af_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py311h902ca64_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pynndescent=0.5.13=pyhd8ed1ab_1
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pyparsing=3.3.1=pyhcf101f3_0
  - pyranges=0.0.127=pyh7cba7a3_0
  - pyrle=0.0.42=py311haab0aaa_1
  - pysam=0.23.3=py311hb456a96_1
  - pyscenic=0.12.1=pyhdfd78af_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.8=hab00c5b_0_cpython
  - python-annoy=1.17.3=py311h1ddb823_3
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.11.14=hd8ed1ab_2
  - python-igraph=0.11.9=py311h1ddb823_3
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pywavelets=1.8.0=py311h9f3472d_0
  - pyyaml=6.0.3=py311h3778330_0
  - pyzmq=27.1.0=py311h2315fbb_0
  - r-base=4.5.2=h835929b_3
  - ray-core=2.52.1=py311h0edc2b5_0
  - ray-default=2.52.1=py311h4910f2b_0
  - re2=2025.06.26=h9925aae_0
  - readline=8.3=h853b02a_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhcf101f3_1
  - requests_cache=0.4.13=py_0
  - rich=14.2.0=pyhcf101f3_0
  - rich-argparse=1.7.2=pyhd8ed1ab_0
  - rpds-py=0.30.0=py311h902ca64_0
  - rsa=4.9.1=pyhd8ed1ab_0
  - s2n=1.5.22=h96f233e_0
  - scanorama=1.7.4=pyhdfd78af_0
  - scanpy=1.10.4=pyhd8ed1ab_0
  - scatac-fragment-tools=0.1.4=py311h33b73ba_0
  - scikit-image=0.20.0=py311h2872171_1
  - scikit-learn=1.7.2=py311hc3e1efb_0
  - scipy=1.11.4=py311h64a7726_0
  - scrublet=0.2.3=pyh5e36f6f_1
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - sed=4.9=h6688a6e_0
  - session-info=1.0.0=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - smart_open=7.5.0=pyhcf101f3_0
  - snappy=1.2.2=h03e3b7b_1
  - sorted_nearest=0.0.41=py311haab0aaa_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.8.1=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.6=py311h0372a8f_0
  - stdlib-list=0.12.0=pyhd8ed1ab_0
  - sysroot_linux-64=2.39=hc4b9eeb_5
  - tabulate=0.9.0=pyhcf101f3_3
  - tbb=2022.3.0=h8d10470_1
  - tblib=3.2.2=pyhcf101f3_0
  - texttable=1.7.0=pyhd8ed1ab_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tifffile=2020.6.3=py_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tktable=2.10=h8d826fa_7
  - tmtoolkit=0.12.0=pyhcf101f3_1
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.4=py311h41d9c34_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_inspect=0.9.0=pyhd8ed1ab_1
  - tzdata=2025c=hc9c84f9_1
  - umap-learn=0.5.9.post2=py311h38be061_1
  - unicodedata2=17.0.0=py311h49ec1c0_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - virtualenv=20.35.4=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.3=py311h49ec1c0_1
  - xlrd=2.0.2=pyhd8ed1ab_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - yarl=1.22.0=py311h3778330_0
  - zeromq=4.3.5=h387f397_9
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.3.2=hceb46e0_1
  - zstandard=0.25.0=py311haee01d2_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - lda==3.0.2
prefix: /home/victorffernandes/miniforge3/envs/scenicplus_obj
