name: scenicplus_v3
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.19=py311hdb0dbe3_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - icu=78.1=h33c6efd_0
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.9.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgomp=15.2.0=he0feb66_16
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.1=hf4e2dac_1
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libuuid=2.41.3=h5347b49_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.1=py311haee01d2_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.14=hd63d673_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=8_cp311
  - pyzmq=27.1.0=py311h2315fbb_0
  - readline=8.3=h853b02a_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=noxft_ha0e22de_103
  - tornado=6.5.4=py311h41d9c34_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zeromq=4.3.5=h387f397_9
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - attrs==25.4.0
      - bidict==0.23.1
      - cattrs==25.3.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - et-xmlfile==2.0.0
      - filelock==3.20.2
      - fonttools==4.61.1
      - future==1.0.0
      - globre==0.1.5
      - idna==3.11
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - llvmlite==0.46.0
      - matplotlib==3.10.8
      - msgpack==1.1.2
      - natsort==8.4.0
      - ncls==0.0.70
      - numba==0.63.1
      - numpy==1.26.4
      - openpyxl==3.1.5
      - pandas==2.3.3
      - pillow==12.1.0
      - polars==1.36.1
      - polars-runtime-32==1.36.1
      - protobuf==6.33.2
      - pyarrow==22.0.0
      - pybiomart==0.2.0
      - pycistopic==3.0
      - pyparsing==3.3.1
      - pyranges==0.1.4
      - pytz==2025.2
      - pyyaml==6.0.3
      - ray==2.53.0
      - referencing==0.37.0
      - requests==2.32.5
      - requests-cache==1.2.1
      - rpds-py==0.30.0
      - scipy==1.16.3
      - sorted-nearest==0.0.41
      - tabulate==0.9.0
      - tmtoolkit==0.12.0
      - tzdata==2025.3
      - url-normalize==2.2.1
      - urllib3==2.6.3
      - xlrd==2.0.2
prefix: /home/victorffernandes/miniforge3/envs/scenicplus_v3
